### ISSUE TITLE
One's

### ISSUE THREAD

**Issue by weaversa** [dylanmc/CryptoBook#1]
Sometimes ones (as in ones and zeroes) is written "one's".

**Comment by yav** [comment]
Using "one's" instead of "ones" is a common mistake.  The apostrophe signifies possessive case as in "one's hat", and it is sometimes used for contractions as in "bottle o' rum" but it is not used for making words plural.

**Comment by weaversa** [comment]
To be more specific, here is an example from Chapter 2:

```...You've heard (most likely) that computers work with ones and zeros. One's and zeros are not very helpful by themselves...```

**Comment by yav** [comment]
Aha, I misunderstood your comment---I thought it was suggesting that "ones" should be replaced by "one's" when, in fact, it was just pointing out the mistake.   Sorry for the noise.

**Comment by dylanmc** [comment]
In addition to this one, a friend suggested I run a spell checker (eeek!). Indeed ispell found a ton of stuff, but not the one's, so they've now been fixed. My brain sees it as possessive: the place belongs to one, but I see that this is not proper usage. Fixed.
